spring:
  application:
    name: ecerp
  profiles:
    active: dev
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  datasource:
#    druid:
#      # 初始连接数
#      initialSize: 5
#      # 最小连接池数量
#      minIdle: 10
#      # 最大连接池数量
#      maxActive: 20
#      # 配置获取连接等待超时的时间
#      maxWait: 60000
#      # 配置连接超时时间
#      connectTimeout: 30000
#      # 配置网络超时时间
#      socketTimeout: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      timeBetweenEvictionRunsMillis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      # 配置一个连接在池中最大生存的时间，单位是毫秒
#      maxEvictableIdleTimeMillis: 900000
#      # 配置检测连接是否有效
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      webStatFilter:
#        enabled: true
#      statViewServlet:
#        enabled: true
#        # 设置白名单，不填则允许所有访问
#        allow:
#        url-pattern: /druid/*
#        # 控制台管理用户名和密码
#        login-username: qihang
#        login-password: 123456
#      filter:
#        stat:
#          enabled: true
#          # 慢SQL记录
#          log-slow-sql: true
#          slow-sql-millis: 1000
#          merge-sql: true
#        wall:
#          config:
#            multi-statement-allow: true
#      username: qihang
#      password: Andy_123



    url: jdbc:h2:file:./db/qihang-ecerp
    driver-class-name: org.h2.Driver
    username: qihang
    password: Andy_123
  h2:
    console:
      enabled: true


#nacos:
#  config:
#    server-addr: 127.0.0.1:8848

#nacos:
#  config:
#    type: yaml
#    server-addr: 127.0.0.1:8848
#    context-path: nacos
#    data-id: ecerp-dev
#    auto-refresh: true
#    bootstrap:
#      enable: true

## 项目相关配置
#zhijian:
#  # 名称
#  name: zhijian
#  # 版本
#  version: 0.1.0
#  # 版权年份
#  copyrightYear: 2024
#  # 实例演示开关
#  demoEnabled: true
#  # 文件路径 示例（ Windows配置D:/zhijian/uploadPath，Linux配置 /home/zhijian/uploadPath）
##  profile: D:/zhijian/uploadPath
#  # 获取ip地址开关
#  addressEnabled: false
#  # 验证码类型 math 数字计算 char 字符验证
#  captchaType: math
#
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
#
## 日志配置
#logging:
#  level:
#    com.zhijian: debug
#    org.springframework: warn
#
# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10
#
## Spring配置
#spring:
#  # 资源信息
#  messages:
#    # 国际化资源文件路径
#    basename: i18n/messages
#  profiles:
#    active: druid
#  # 文件上传
#  servlet:
#    multipart:
#      # 单个文件大小
#      max-file-size: 10MB
#      # 设置总上传的文件大小
#      max-request-size: 20MB
#  # 服务模块
##  devtools:
##    restart:
##      # 热部署开关
##      enabled: true
#  # redis 配置
#  redis:
#    # 地址
##    host: 8.130.98.215
#    host: 127.0.0.1
#    # 端口，默认为6379
#    port: 6379
#    # 数据库索引
#    database: 0
#    # 密码
##    password: 123321
#    # 连接超时时间
#    timeout: 10s
#    lettuce:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池的最大数据库连接数
#        max-active: 8
#        # #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
#
#
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

## MyBatis配置
##mybatis:
##  # 搜索指定包别名
##  typeAliasesPackage: com.zhijian.**.domain;com.qihang.erp.api.domain
##  # 配置mapper的扫描，找到所有的mapper.xml映射文件
##  mapperLocations: classpath*:mapper/**/*Mapper.xml
##  # 加载全局的配置文件
##  configLocation: classpath:mybatis/mybatis-config.xml

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.zhijian.**.domain;com.qihang.erp.api.domain
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志
#  config-location: classpath:mybatis/mybatis-config.xml

#### # mybatis mapper路径 适用于 mybatis 和 mybatis-plus
##mybatis.mapper-locations=classpath*:mappers/*.xml
##
### mybatis-plus mapper路径  适用于 mybatis-plus-boot-starter
##mybatis-plus.mapper-locations=classpath*:mappers/*.xml
#
#
# PageHelper分页插件
#pagehelper:
#  helperDialect: mysql
#  supportMethodsArguments: true
#  params: count=countSql

### Swagger配置
##swagger:
##  # 是否开启swagger
##  enabled: true
##  # 请求前缀
##  pathMapping: /dev-api
#
# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

#minio:
#  endpoint: http://127.0.0.1:9000 #换成自己的minio服务端地址
#  accessKey: 0AksAWDtI20Lpb4qxq5S
#  secretKey: yOAZkOVwrhPooBRel5PB0GwS5uw8VAgmqYykHl3T
#  secure: false
#  bucketName: ecerp
#
##spider:
##  thread:
##    count: 5